"""予約ユースケースが必要とする出力ポート。"""
from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol
from restaurant.domain import Proposal, Reservation, Table


class Clock(Protocol):
    def now(self) -> datetime: ...


class ReservationRepository(Protocol):
    def transaction(self) -> AbstractAsyncContextManager[None]:
        """再確認・提案消費・予約更新を同じ排他境界内で実行する。"""
        ...

    def tables(self) -> list[Table]: ...
    def reservations(self) -> list[Reservation]: ...
    def get_reservation(self, reservation_id: str) -> Reservation | None: ...
    def save_reservation(self, reservation: Reservation) -> None: ...
    def get_proposal(self, proposal_id: str) -> Proposal | None: ...
    def save_proposal(self, proposal: Proposal) -> None: ...
